const Spinner = () => {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            style={{ margin: "auto" }}
            width="100"
            height="100"
            display="block"
            preserveAspectRatio="xMidYMid"
            viewBox="0 0 100 100"
            >
        <rect width="6" height="20" x="47" y="14" fill="#9b3430" rx="3" ry="10">
            <animate
            attributeName="opacity"
            begin="-1.2937595129375952s"
            dur="1.36986301369863s"
            keyTimes="0;1"
            repeatCount="indefinite"
            values="1;0"
            ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#aeb7c2"
                rx="3"
                ry="10"
                transform="rotate(20 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-1.21765601217656s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#3b5fa4"
                rx="3"
                ry="10"
                transform="rotate(40 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-1.1415525114155252s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#171b31"
                rx="3"
                ry="10"
                transform="rotate(60 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-1.06544901065449s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#9b3430"
                rx="3"
                ry="10"
                transform="rotate(80 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-0.989345509893455s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#aeb7c2"
                rx="3"
                ry="10"
                transform="rotate(100 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-0.91324200913242s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#3b5fa4"
                rx="3"
                ry="10"
                transform="rotate(120 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.837138508371385s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#171b31"
                rx="3"
                ry="10"
                transform="rotate(140 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.76103500761035s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#9b3430"
                rx="3"
                ry="10"
                transform="rotate(160 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-0.684931506849315s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#aeb7c2"
                rx="3"
                ry="10"
                transform="rotate(180 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-0.60882800608828s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#3b5fa4"
                rx="3"
                ry="10"
                transform="rotate(200 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-0.532724505327245s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#171b31"
                rx="3"
                ry="10"
                transform="rotate(220 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-0.45662100456621s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#9b3430"
                rx="3"
                ry="10"
                transform="rotate(240 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-0.380517503805175s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#aeb7c2"
                rx="3"
                ry="10"
                transform="rotate(260 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-0.30441400304414s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#3b5fa4"
                rx="3"
                ry="10"
                transform="rotate(280 50 50)"
            >
                <animate
                    attributeName="opacity"
                    begin="-0.228310502283105s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
            </rect>
        <rect
                width="6"
                height="20"
                x="47"
                y="14"
                fill="#171b31"
                rx="3"
                ry="10"
                transform="rotate(300 50 50)"
        >
                <animate
                    attributeName="opacity"
                    begin="-0.15220700152207s"
                    dur="1.36986301369863s"
                    keyTimes="0;1"
                    repeatCount="indefinite"
                    values="1;0"
                ></animate>
        </rect>
        <rect
            width="6"
            height="20"
            x="47"
            y="14"
            fill="#9b3430"
            rx="3"
            ry="10"
            transform="rotate(320 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.076103500761035s"
                dur="1.36986301369863s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            ></animate>
        </rect>
        <rect
            width="6"
            height="20"
            x="47"
            y="14"
            fill="#aeb7c2"
            rx="3"
            ry="10"
            transform="rotate(340 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="0s"
                dur="1.36986301369863s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            ></animate>
         </rect>
        </svg>
    )
}

export default Spinner;